language: python
python:
  - "3.7"
env:
  global:
    - NEWEST_PYTHON=3.7
install:
  - pip install -e .
script:
  - DOCKER=FALSE make lint
  - DOCKER=FALSE make type-check
  - DOCKER=FALSE make test
  - DOCKER=FALSE make coverage
notifications:
email: false
